version: "3.9"

services:
  php:
    build: ./php-docker
    volumes:
      - .:/webapp
    restart: unless-stopped
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/webapp
      - ./site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    tty: true
    depends_on:
      - php